#lang racket
(display "Задание 1. \nВычисление стоимости поездки на дачу и обратно.")
(display "\nВведите расстояние до дачи: ")
(define S (read))
(display "Количество бензина, которое потребляет автомобиль на 100 км пробега: ")
(define l (read))
(display "Цена одного литра бензина: ")
(define p (read))
(define out (* (* (/ S 100) l) p))
(display "Стоймость поездки: ")
(display out)
(display " рублей.")

(display "\n\nЗадание 2. \nВычисление объема цилиндра.")
(display "\nВведите исходные данные: ")
(display "\nрадиус основания (см) = ")
(define r (read))
(display "высота цилиндра (см) = ")
(define h (read))
(define vol (* (* 3.14 h) (* r r)))
(display "Объем цилиндра ")
(display vol)
(display " см.куб")

(display "\n\nЗадание 3. \nВычисление сопротивления электрической цепи.")
(display "\nВведите исходные данные:")
(display "\nВеличина первого сопротивления (Ом) = ")
(define r1 (read))
(display "Величина второго сопротивления (Ом) = ")
(define r2 (read))
(printf "Сопротивление цепи: ~a Ом" (/ (* r1 r2) (* (+ r1 r2) 1.0)))