#lang racket
(display  "Задание 1. Вычисление площади кольца. " )
(display "\nРадиус кольца (>=5): ")
(define R (read))
(display "Радиус отверстия (>=6): ")
(define r (read))
(if (and (>= R 5) (>= r 6) (> R r))
(and(display "Площадь круга: ")(display (* (- (* R R) (* r r)) 3.14)))
(display "Ошибка ввода или радиус отверстия больше радиуса кольца!"))

(display  "\n\nЗадание 2. В каком году началась вторая мировая война?" )
(display "\nВведите год: ")
(define y (read))
(if (= y 1939)
    (display "Верно")
(display "Неверно. Начало - 1939 год"))

(display  "\n\nЗадание 3. Сравнение двух чисел." )
(display "\nВведите в одной строке два целых числа: ")
(define a (read))
(define b (read))
(if (> a b)
(printf "~a больше ~a" a b)
(if (< a b)
(printf "~a меньше ~a" a b)
(display "Числа равны")))