#lang racket
(display  "Правило: При вводе отрицательного числа - делать положительным с умножением на заданное число")
(display  "\nВведите чесло: ")
(define value (read))
(display  "Введите модуль умножения: ")
(define pow (read))
(display  "функция: ")
(define (moduls value)
(if (< value 0)
(display (* (* value pow) -1)) value))
(moduls value)
(display  "\nlet: ")
(let mod ((pow value))
(if (* (* value pow) -1) 
  (display (* value pow))
    value))
(display  "\nlambda: ")
(if (< value 0)
((lambda (value) (* (* value pow) -1))
   value) value )